### ISSUE TITLE
__pycache__	folders committed to github

### ISSUE THREAD

**Issue by ghost** [tyshsh/web_crawler#1]
not really an issue but these are compiled bytecode and are specific to your version of python. There's no requirements.txt file to try this project out, nor any Dockerfile which would let me run the code.

**Comment by tyshsh** [comment]
Thanks for the issue report. The structure of this repo has been cleaned and reorganized. Please clone it again in order to fresh it. The "requirements.txt" file is also prepared, as well as an updated README.md file with more detailed instructions.
